# Generated by Django 2.0.6 on 2018-06-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_choice_choice_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='updated',
        ),
    ]
